### ISSUE TITLE
undefined local variable or method `max_per_page'

### ISSUE THREAD

**Issue by simoncorreaocampo** [thambley/activeadmin-xls#2]
Hi, I am receiving the next error:
`NameError (undefined local variable or method `max_per_page' for #<Admin::UsersController:0x000000065f4cd0>):
  vendor/bundle/ruby/2.2.0/bundler/gems/activeadmin-xls-87675360866b/lib/active_admin/xls/resource_controller_extension.rb:26:in `per_page_with_xls'`

**Comment by rewritten** [comment]
See #3
