### ISSUE TITLE
only_columns in addition to delete_columns

### ISSUE THREAD

**Issue by seanfcarroll** [thambley/activeadmin-xls#7]
A nice feature would be the abilty to name the columns in the order they should appear in the file. As I understand it, it is only possible to delete columns, eg:

    config.xls_builder.delete_columns :id, :created_at, :updated_at, :category_name, :epfl_id_inst, :epfl_id_transact, :epfl_result, :epfl_date_cr, :epfl_payment_cd, :epfl_paymode, :epfl_payment_status_cd, :

It would be nice to be able to also do this

     config.xls_builder.only_columns :first_name, :last_name, :organization, :email, :payment

**Comment by seanfcarroll** [comment]
This works

     config.xls_builder.whitelist    # clear the list
     config.xls_builder.column(:first_name)
     config.xls_builder.column(:first_name)

But this doesn't

     config.xls_builder.whitelist    # clear the list
     config.xls_builder do
        column :first_name
        column :last_name
     end

**Comment by Bernhard** [comment]
You could also use:

```
  xls do
    whitelist
    column(:first_name)
    column :last_name
end
```

Attention: it's `xls` not `xlsx` as written in the readme.

**Comment by thambley** [comment]
I will try to add an `only_columns` method soon.

There are currently 2 mutually exclusive patterns for working with the xls_builder.

This one:

```ruby
 config.xls_builder.whitelist    # clear the list
 config.xls_builder.column(:first_name)
 config.xls_builder.column(:first_name)
```

or the DSL method:

```ruby
xls do
  whitelist
  column(:first_name)
  column(:last_name)
end
```

The DSL method `xls` replaces the config.xls_builder object with a newly initialized xls_builder object.

```ruby
def xls(options = {}, &block)
  config.xls_builder = ActiveAdmin::Xls::Builder.new(
    config.resource_class,
    options,
    &block
  )
end
```

This behavior is consistent with the built-in ActiveAdmin csv functionality and activeadmin-axlsx functionality although not necessarily expected and I will document that as well.

**Comment by thambley** [comment]
only_columns added in 1.1
